### ISSUE TITLE
Reaching out to Rsocket community 

### ISSUE THREAD

**Issue by smaldini** [flier/rsocket-go#1]
Hey @flier we are trying to federate an effort around rsocket-go and your implementation is already pretty advanced. Would you have time to discuss with the rsocket work group ? We can invite you in the rsocket slack if you share your mail address (we haven't setup self registration yet) : you can ping me via DM or `smaldini ----- at ..... pivotal.io`

Hope to read from you !

**Comment by flier** [comment]
sorry, I'm not very familiar with Slack, how can I send DM to you? It seems I can't find your account in Slack client, maybe you can direct invite me (flier.lu ---- at +++++ gmail.com)

**Comment by smaldini** [comment]
Sent a msg.Thanks !
